apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: azuredisk-csi-driver
  namespace: kube-system
spec:
  chart: azuredisk-csi-driver
  repo: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
  targetNamespace: kube-system
  version: v1.8.0
  valuesContent: |-

    controller:
      runOnMaster: false
      replicas: 1
      logLevel: 6

    linux:
      enabled: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS  # alias: storageaccounttype, available values: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true