apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart: external-dns
  repo: https://charts.bitnami.com/bitnami
  valuesContent: |-
    policy: sync
    txtOwnerId: ${dns_auth.domain}
    domainFilters:
      - ${dns_auth.domain}
%{ if dns_auth.provider == "cloudflare" ~}
      - ${dns_auth.zone}
%{ endif ~}
    policy: sync
    interval: 2m
    logLevel: debug
    txtPrefix: exdns.
    replicas: 1
    image:
      registry: gcr.io
      repository: k8s-staging-external-dns/external-dns
      tag: v20210720-v0.8.0-121-gf9a3fe3d
    extraEnv:
      - name: EXTERNAL_DNS_TXT_WILDCARD_REPLACEMENT
        value: wild
%{ if dns_auth.provider == "digitalocean" ~}
    provider: digitalocean
    digitalocean:
      apiToken: ${dns_auth.token}
%{ endif ~}
%{ if dns_auth.provider == "cloudflare" ~}
    zoneIdFilters:
      - ${dns_auth.zone_id}
    provider: cloudflare
    cloudflare:
      apiKey: ${dns_auth.api_token}
      email: ${dns_auth.email}
%{ endif ~}
